include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = SBTweakerPrefs
SBTweakerPrefs_FILES = SBTRootListController.m SBTNumberCell.m
SBTweakerPrefs_FRAMEWORKS = UIKit
SBTweakerPrefs_PRIVATE_FRAMEWORKS = Preferences
SBTweakerPrefs_INSTALL_PATH = /Library/PreferenceBundles
SBTweakerPrefs_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/bundle.mk
